spring:
  application:
    name: estoque-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: estoque-group
      key-deserializer: org.apache.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest

